sequenceDiagram
    actor User
    participant ScooterApp
    participant Scooter
    
    User ->> ScooterApp: Create Account
    activate ScooterApp
    alt has account
        ScooterApp -->> User: Already registered response
    else under 18
        ScooterApp -->> User: Too young response
    else 
        ScooterApp -->> User: Register User
    end
    deactivate ScooterApp

    User ->> ScooterApp: Log In
    activate ScooterApp
    alt is registered
        ScooterApp -->> User: No user response
    else incorrent credentials
        ScooterApp -->> User: Incorrect credentials response
    else 
        ScooterApp -->> User: Log in user
    end
    deactivate ScooterApp

    User ->> ScooterApp: request to rent Scooter
    activate ScooterApp
    alt find scooter
        activate Scooter
        ScooterApp ->> Scooter: find scooter
        Scooter -->> Scooter: generate scooter
        ScooterApp ->> Scooter: update location
        alt no location
            Scooter -->> Scooter: error
        end
        alt location given
            ScooterApp ->> Scooter: update user
            Scooter -->> Scooter: check charge    
            Scooter -->> ScooterApp: return low charge
            Scooter -->> Scooter: broken
            Scooter -->> ScooterApp: return broken status
        end
        deactivate Scooter
    end
    ScooterApp -->> User: rent scooter
    deactivate ScooterApp


    User ->> Scooter: Return Scooter
    activate Scooter
    alt remove scooter
        Scooter -->> ScooterApp: find scooter in database
        deactivate Scooter
        activate ScooterApp
        ScooterApp -->> ScooterApp: remove scooter from database
    end
    ScooterApp -->> User: return scooter
    deactivate ScooterApp